Repository Sexy-Sisters/TOJ-server-v2, pull requests merged in 2022-12, with the labels that each got.

#53 Feat/school
  build.gradle.kts
  src/main/kotlin/com/sexysisters/tojserverv2/application/school/SchoolFacade.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/FeignClientErrorDecoder.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/neis/client/NeisSchoolInfoClient.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/neis/dto/NeisSchoolInfoResponse.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/neis/properties/NeisParamProperty.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/neis/properties/NeisRequestProperty.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/oauth/client/GoogleAuthClient.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/oauth/client/GoogleInfoClient.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/oauth/dto/GoogleCodeRequest.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/oauth/dto/GoogleInfoResponse.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/oauth/dto/TokenResponse.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/oauth/exception/OAuthErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/oauth/exception/OtherServerBadRequestException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/oauth/exception/OtherServerExpiredTokenException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/oauth/exception/OtherServerForbiddenException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/oauth/exception/OtherServerUnauthorizedException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/config/FeginConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/config/SecurityConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/config/WebMvcConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/School.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/SchoolCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/SchoolInfo.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/SchoolMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/design/SchoolReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/design/SchoolStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolExcpetion.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/type/Division.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/type/Kind.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/User.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/UserCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/exception/EmailAlreadyExistsException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/service/AuthServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/type/ApplyStatus.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/type/Authority.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/neis/NeisSchoolReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/neis/NeisSchoolReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/neis/dto/NeisSchoolMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/neis/dto/NeisSchoolResponse.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/oauth/GoogleAuthExecutor.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/school/SchoolReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/school/SchoolRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/school/SchoolStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/SchoolApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolRequest.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolResponse.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/user/UserApiController.kt
  src/main/resources/application.yml
  src/test/kotlin/com/sexysisters/tojserverv2/domain/user/service/UserServiceTest.kt
Labels: ⚡️FEAT, ♻️ REFACTOR, ⚒️ FIX, ⚙️SET

#55 Validate User When User Sign-up
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/design/UserReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/exception/EmailAlreadyExistsException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/exception/NicknameAlreadyExistsException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/exception/PasswordMismatchException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/exception/UserException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/exception/UserNotFoundException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/service/AuthServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/user/UserReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/user/UserStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/user/AuthApiController.kt
Labels: ⚡️FEAT

#58 Feat/school
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/School.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/SchoolCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/SchoolInfo.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/SchoolMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolExcpetion.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/type/ApplyStatus.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/SchoolApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolResponse.kt
Labels: ⚡️FEAT, ♻️ REFACTOR

#61 Refactor/student
  src/main/kotlin/com/sexysisters/tojserverv2/application/school/SchoolFacade.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/School.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/SchoolCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/SchoolInfo.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/SchoolMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/design/SchoolReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/design/StudentReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/design/StudentStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/StudentService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/StudentServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/student/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/User.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/UserCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/service/OAuthServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/type/ApplyStatus.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/neis/NeisSchoolReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/neis/NeisSchoolReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/school/SchoolReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/school/student/StudentReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/school/student/StudentRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/school/student/StudentStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/SchoolApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolRequest.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolResponse.kt
  src/test/kotlin/com/sexysisters/tojserverv2/domain/user/service/AuthServiceTest.kt
Labels: ♻️ REFACTOR, ⚒️ FIX

#64 Refactor
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/School.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/exception/StudentErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/exception/StudentException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/User.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/exception/UserErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/exception/UserException.kt
Labels: ♻️ REFACTOR

#65 [Feat/auth] Get New Access Token
  build.gradle.kts
  src/main/kotlin/com/sexysisters/tojserverv2/config/SecurityConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/auth/AuthCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/auth/AuthInfo.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/auth/exception/AuthErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/auth/exception/AuthException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/auth/service/AuthService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/auth/service/AuthServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/UserCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/UserInfo.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/exception/UserErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/exception/UserException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/service/AuthService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/service/OAuthService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/service/OAuthServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/jwt/JwtValidator.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/auth/AuthApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/auth/dto/AuthDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/auth/dto/AuthRequest.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/auth/dto/AuthResponse.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/user/OAuthApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/user/dto/UserDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/user/dto/UserRequest.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/user/dto/UserResponse.kt
  src/main/resources/application.yml
  src/test/kotlin/com/sexysisters/tojserverv2/domain/auth/service/AuthServiceTest.kt
Labels: ⚡️FEAT, ♻️ REFACTOR

#67 fix: search school (request body -> param)
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/SchoolCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/SchoolApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolDtoMapper.kt
Labels: ⚒️ FIX

#69 [Fix/domain policy]
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/AlreadyExistsStudentPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/AlreadyJoinedPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/SchoolPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/StudentReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/policy/AlreadyCreatedPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/policy/StudentPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/service/StudentServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/student/StudentReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/student/StudentRepository.kt
Labels: ⚡️FEAT, ♻️ REFACTOR

#70 Feat/approve
  build.gradle.kts
  src/main/kotlin/com/sexysisters/tojserverv2/application/school/SchoolFacade.kt
  src/main/kotlin/com/sexysisters/tojserverv2/config/QueryDslConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/Approve.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/ApproveCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/ApproveReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/ApproveStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/exception/ApproveErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/exception/ApproveException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/policy/AlreadyJoinedPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/policy/ApproveCountPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/policy/ApprovePolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/policy/SameSchoolPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/service/ApproveService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/service/ApproveServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/AlreadyExistsStudentPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/DirectJoinPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/InfoRangePolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/SchoolPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/approve/ApproveRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/approve/ApproveStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/student/StudentCustomRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/student/StudentCustomRepositoryImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/student/StudentRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/approve/ApproveApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/approve/dto/ApproveDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/approve/dto/ApproveRequest.kt
Labels: ⚡️FEAT, ♻️ REFACTOR, ⚒️ FIX

#71 feat: approve cancel
  src/main/kotlin/com/sexysisters/tojserverv2/config/SecurityConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/Approve.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/ApproveCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/ApproveReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/ApproveStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/exception/ApproveErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/exception/ApproveException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/service/ApproveService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/service/ApproveServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/approve/ApproveReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/approve/ApproveRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/approve/ApproveStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/approve/ApproveApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/approve/dto/ApproveDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/approve/dto/ApproveRequest.kt
Labels: ⚡️FEAT

#74 Fix/bug
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/neis/client/NeisSchoolInfoClient.kt
  src/main/kotlin/com/sexysisters/tojserverv2/config/SecurityConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/ApproveCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/SchoolInfo.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/neis/NeisSchoolReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/neis/NeisSchoolReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/SchoolApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolResponse.kt
Labels: ♻️ REFACTOR, ⚒️ FIX

#77 fix: (#76) put together waiting student list API and engaged student …
  src/main/kotlin/com/sexysisters/tojserverv2/config/SecurityConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/config/WebMvcConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/StudentReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/service/StudentService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/service/StudentServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/student/StudentReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/student/StudentRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/approve/ApproveApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/image/ImageApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/SchoolApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/student/StudentApiController.kt
Labels: ⚒️ FIX

#80 Feat/school wiki
  src/main/kotlin/com/sexysisters/tojserverv2/application/school/SchoolFacade.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/security/auth/AuthDetailsService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/auth/service/AuthServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/School.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/service/StudentServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/UserReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/UserStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/design/UserStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/service/OAuthServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/service/UserServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/Wiki.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/WikiCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/WikiInfo.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/WikiMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/WikiReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/WikiStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/exception/WikiErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/exception/WikiException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/policy/UpdateAuthority.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/policy/WikiPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/service/WikiService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/service/WikiServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/student/StudentReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/user/UserReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/user/UserStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/wiki/WikiReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/wiki/WikiRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/wiki/WikiStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/wiki/WikiApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/wiki/dto/WikiDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/wiki/dto/WikiRequest.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/wiki/dto/WikiResponse.kt
  src/test/kotlin/com/sexysisters/tojserverv2/domain/auth/service/AuthServiceTest.kt
  src/test/kotlin/com/sexysisters/tojserverv2/domain/user/service/UserServiceTest.kt
Labels: ⚡️FEAT

#82 Set CI
  .github/workflows/CI.yml
  build.gradle.kts
  src/main/kotlin/com/sexysisters/tojserverv2/config/SecurityConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/image/s3/Dir.kt
  src/test/kotlin/com/sexysisters/tojserverv2/domain/auth/service/AuthServiceTest.kt
  src/test/kotlin/com/sexysisters/tojserverv2/domain/user/service/UserServiceTest.kt
Labels: ⚒️ FIX, 🧶CHORE

#83 feat: create teacher domain
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/School.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/exception/TeacherErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/exception/TeacherException.kt
Labels: ⚡️FEAT

#89 Feat/ad
  src/main/kotlin/com/sexysisters/tojserverv2/config/SecurityConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/ad/AdCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/ad/AdReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/ad/AdStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/ad/domain/Ad.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/ad/domain/Company.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/ad/domain/CostInfo.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/ad/exception/AdErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/ad/exception/AdException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/ad/service/AdService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/ad/service/AdServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/ad/AdReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/ad/AdRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/ad/AdStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/ad/AdApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/ad/dto/AdDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/ad/dto/AdRequest.kt
Labels: ⚡️FEAT

#92 Fix/swagger message
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/ad/AdApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/approve/ApproveApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/image/ImageApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/SchoolApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/student/StudentApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/wiki/WikiApiController.kt
Labels: ♻️ REFACTOR

#96 Fix/school wiki
  src/main/kotlin/com/sexysisters/tojserverv2/config/properties/WikiProperties.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/ad/domain/CostInfo.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/School.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/User.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/Wiki.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/WikiCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/WikiInfo.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/service/WikiServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/wiki/dto/WikiRequest.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/wiki/dto/WikiResponse.kt
Labels: ♻️ REFACTOR, ⚒️ FIX

#97 Feat/teacher
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Bio.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Image.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Name.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Nickname.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/TeacherCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/TeacherEntityMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/TeacherStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/exception/TeacherErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/exception/TeacherException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/service/TeacherService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/service/TeacherServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/User.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/teacher/TeacherRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/teacher/TeacherStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/teacher/TeacherApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/teacher/dto/TeacherDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/teacher/dto/TeacherRequest.kt
Labels: ⚡️FEAT

#99 refactoring
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/oauth/client/GoogleInfoClient.kt
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/api/oauth/dto/OAuthInfoResponse.kt
  src/main/kotlin/com/sexysisters/tojserverv2/config/RedisConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/config/SecurityConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/config/properties/WikiProperties.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/service/OAuthServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/jwt/JwtTokenProvider.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/jwt/JwtTokenProviderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/jwt/JwtValidator.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/jwt/JwtValidatorImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/oauth/GoogleAuthExecutorImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/oauth/OAuthExecutor.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/oauth/OAuthMethod.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/redis/RedisRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/redis/RedisRepositoryImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/image/ImageApiController.kt
Labels: ♻️ REFACTOR, ⚒️ FIX

#104 refactor: make the URL a constant
  src/main/kotlin/com/sexysisters/tojserverv2/application/school/SchoolFacade.kt
  src/main/kotlin/com/sexysisters/tojserverv2/config/SecurityConfiguration.kt
  src/main/kotlin/com/sexysisters/tojserverv2/config/properties/WikiProperties.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/domain/Address.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/domain/Belong.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/domain/Code.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/domain/Name.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/domain/Phone.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/domain/School.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/domain/HTML.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/domain/Markdown.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/domain/Name.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/domain/Views.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/domain/Wiki.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/service/WikiServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/neis/NeisSchoolReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/school/SchoolReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/school/SchoolRepository.kt
Labels: ♻️ REFACTOR

#105 Feat/teacher
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/StudentMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/domain/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/TeacherCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/TeacherEntityMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/TeacherReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/TeacherResponseMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/TeacherStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/domain/Bio.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/domain/Image.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/domain/Name.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/domain/Nickname.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/domain/Teacher.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/exception/TeacherErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/exception/TeacherException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/service/TeacherService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/service/TeacherServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/Email.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/Image.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/Name.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/Password.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/User.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/UserCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/type/Nickname.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/teacher/TeacherCustomRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/teacher/TeacherCustomRepositoryImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/teacher/TeacherReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/teacher/TeacherStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/teacher/TeacherApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/teacher/dto/TeacherDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/teacher/dto/TeacherRequest.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/teacher/dto/TeacherResponse.kt
Labels: ⚡️FEAT

#106 refactor: (#101) wrap primitive type of User domain
  src/main/kotlin/com/sexysisters/tojserverv2/common/security/auth/AuthDetails.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/auth/service/AuthServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/AlreadyExistsStudentPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/InfoRangePolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/domain/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/policy/AlreadyCreatedPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/policy/StudentPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/service/TeacherServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/UserCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/UserMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/UserReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/UserStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/domain/Authority.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/domain/Email.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/domain/Image.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/domain/Name.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/domain/Nickname.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/domain/Password.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/domain/User.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/service/OAuthServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/service/UserServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/type/Authority.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/user/UserReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/user/UserRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/user/UserStoreImpl.kt
  src/test/kotlin/com/sexysisters/tojserverv2/domain/auth/service/AuthServiceTest.kt
  src/test/kotlin/com/sexysisters/tojserverv2/domain/user/service/UserServiceTest.kt
Labels: ♻️ REFACTOR

#108 feat: Get current student
  src/main/kotlin/com/sexysisters/tojserverv2/common/response/CommonControllerAdvice.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/service/StudentService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/service/StudentServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/student/StudentReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/student/StudentApiController.kt
Labels: ⚡️FEAT

#112 Feat/school wallpaper
  src/main/kotlin/com/sexysisters/tojserverv2/config/properties/SchoolProperties.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/SchoolCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/domain/School.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/domain/Wallpaper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/WikiInfo.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/WikiMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/service/WikiServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/neis/dto/NeisSchoolResponse.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/SchoolApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolRequest.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/wiki/WikiApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/wiki/dto/WikiResponse.kt
Labels: ⚡️FEAT, ⚒️ FIX

#113 fix: Add updatedAt property when calling getSchool API
  src/main/kotlin/com/sexysisters/tojserverv2/common/util/date/FormatUtil.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/WikiInfo.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/WikiMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/service/WikiServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/wiki/WikiApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/wiki/dto/WikiResponse.kt
Labels: ⚒️ FIX

#116 Refactor/wiki
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/policy/ApproveCountPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/DirectJoinPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/domain/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/policy/AlreadyCreatedPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/domain/Teacher.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/service/TeacherService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/service/TeacherServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/domain/User.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/service/UserServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/domain/HTML.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/domain/Markdown.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/domain/Views.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/domain/Wiki.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/service/WikiServiceImpl.kt
Labels: ♻️ REFACTOR, ⚒️ FIX

#120 Feat/feed
  src/main/kotlin/com/sexysisters/tojserverv2/config/properties/WikiProperties.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/ad/exception/AdErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/feed/FeedCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/feed/FeedReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/feed/FeedStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/feed/domain/Content.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/feed/domain/Feed.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/feed/domain/Image.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/feed/exception/FeedErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/feed/exception/FeedException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/feed/service/FeedService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/feed/service/FeedServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/domain/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/exception/StudentErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/exception/WikiErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/feed/FeedReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/feed/FeedRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/feed/FeedStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/feed/FeedApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/feed/dto/FeedDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/feed/dto/FeedRequest.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/wiki/dto/WikiResponse.kt
Labels: ⚡️FEAT

#125 feat: (#117) Create teacher comment
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/domain/School.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/domain/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/exception/StudentErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/exception/StudentException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/TeacherCommentCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/TeacherCommentMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/TeacherCommentReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/TeacherCommentStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/domain/Comment.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/domain/Content.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/domain/Teacher.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/exception/TeacherCommentErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/exception/TeacherCommentException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/service/TeacherCommentService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/service/TeacherCommentServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/teacher/TeacherCommentReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/teacher/TeacherCommentRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/teacher/TeacherCommentStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/teacher/TeacherCommentApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/teacher/dto/TeacherCommentDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/teacher/dto/TeacherCommentRequest.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/teacher/dto/TeacherCommentResponse.kt
Labels: ⚡️FEAT

#127 feat: (#126) teacher like
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/domain/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/domain/Comment.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/domain/Teacher.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/service/TeacherCommentServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/service/TeacherServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacherLike/TeacherLikeReader.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacherLike/TeacherLikeStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacherLike/domain/TeacherLike.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacherLike/service/TeacherLikeService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacherLike/service/TeacherLikeServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/teacherLike/TeacherLikeReaderImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/teacherLike/TeacherLikeRepository.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/teacherLike/TeacherLikeStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/teacherLike/TeacherLikeApiController.kt
Labels: ⚡️FEAT

#124 [fix/student] Merge student creation API and school participation API
  src/main/kotlin/com/sexysisters/tojserverv2/application/school/SchoolFacade.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/policy/ApproveCountPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/approve/policy/SameSchoolPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/domain/School.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/exception/SchoolException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/AlreadyExistsStudentPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/DirectJoinPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/InfoRangePolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/policy/SchoolPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolService.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/school/service/SchoolServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/StudentCommand.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/StudentInfo.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/StudentStore.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/domain/Student.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/exception/StudentErrorCode.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/exception/StudentException.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/policy/AlreadyCreatedPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/policy/StudentPolicy.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/student/service/StudentServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/service/TeacherServiceImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/user/domain/User.kt
  src/main/kotlin/com/sexysisters/tojserverv2/domain/wiki/policy/UpdateAuthority.kt
  src/main/kotlin/com/sexysisters/tojserverv2/infrastructure/student/StudentStoreImpl.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/SchoolApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/school/dto/SchoolRequest.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/student/StudentApiController.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/student/dto/StudentDtoMapper.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/student/dto/StudentRequest.kt
  src/main/kotlin/com/sexysisters/tojserverv2/interfaces/student/dto/StudentResponse.kt
Labels: ⚒️ FIX
